name: qlm
channels:
  - defaults
dependencies:
  - ca-certificates=2025.11.4=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.18=h543e019_0
  - pip=24.2=py38haa95532_0
  - python=3.8.20=h8205438_0
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - pip:
    - cffi==1.17.1
    - cryptography==46.0.3
    - mysql-connector-python==9.0.0
    - pycparser==2.23
    - pymysql==1.1.2
    - typing-extensions==4.13.2
prefix: F:\anaconda\envs\qlm
